### ISSUE TITLE
Row too big to fit into CursorWindow

### ISSUE THREAD

**Issue by young310** [tinode/tindroid#104]
**If you are not reporting a bug, please post to https://groups.google.com/d/forum/tinode instead.**
---

**Describe the bug**
When tindroid app try to list the chat history with attachment larger than 2MB, the tindroid app will crash

**To Reproduce**
1. Send a ptt file large than 2MB
2. Read the message from android client (web client seems okay)
3. tindroid App will crash

**Expected behavior**
tindroid App will crash, and you will never get back into the chat window since it crash all the time when you enter the app or the chatting window

**Screenshots**
Because the app crash every time when you click on the chat window, there is not snapshot for now

**Tindroid (please complete the following information):**
 - Version 0.17.0-rc1-1-g8093fb7e 970
 - Device Stock Emulator, Xiaomi Note8pro
 - Android API Version 29/30

**Server**
- Type my own setup
- Server type unmodified using docker
- Server version 0.16 mysql:v0.16.10

**Additional context**
W/CursorWindow: Window is full: requested allocation 3423727 bytes, free space 2096524 bytes, window size 2097152 bytes
E/SQLiteQuery: exception: Row too big to fit into CursorWindow requiredPos=0, totalRows=1; query: SELECT m1.*, t.name AS topic FROM messages AS m1 LEFT JOIN messages AS m2 ON (m1.topic_id=m2.topic_id AND m1.seq<m2.seq) LEFT JOIN topics AS t ON m1.topic_id=t._id WHERE m1.del_id IS NULL AND m2.del_id IS NULL AND m2._id IS NULL
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ultrondata.oncall, PID: 10551
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ultrondata.oncall/co.tinode.tindroid.ChatsActivity}: android.database.sqlite.SQLiteBlobTooBigException: Row too big to fit into CursorWindow requiredPos=0, totalRows=1
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3449)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: android.database.sqlite.SQLiteBlobTooBigException: Row too big to fit into CursorWindow requiredPos=0, totalRows=1
        at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
        at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:1001)
        at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:838)
        at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
        at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:153)
        at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:140)
        at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:231)
        at android.database.AbstractCursor.moveToFirst(AbstractCursor.java:270)
        at co.tinode.tindroid.db.SqlStore$MessageList.<init>(SqlStore.java:543)
        at co.tinode.tindroid.db.SqlStore.getLatestMessagePreviews(SqlStore.java:512)
        at co.tinode.tinodesdk.Tinode.loadTopics(Tinode.java:390)
        at co.tinode.tinodesdk.Tinode.<init>(Tinode.java:229)
        at co.tinode.tindroid.Cache.getTinode(Cache.java:30)
        at co.tinode.tindroid.ChatsActivity.onCreate(ChatsActivity.java:71)
        at android.app.Activity.performCreate(Activity.java:8000)
        at android.app.Activity.performCreate(Activity.java:7984)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7656) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by or-else** [comment]
It's not an android bug. Your server is misconfigured.

**Comment by young310** [comment]
> It's not an android bug. Your server is misconfigured.

I am sorry for the duplicated post in another thread, please help remove them if possible.

**Comment by young310** [comment]
> It's not an android bug. Your server is misconfigured.

Hi

I tried the public server, and it looks like the server will not store files larger 
<img width="401" alt="Screen Shot 2021-04-27 at 11 31 14" src="https://user-images.githubusercontent.com/8056293/116180902-47452900-a74c-11eb-9410-f742196ac634.png">
than 2mb for now, am I correct?
<img width="1461" alt="Screen Shot 2021-04-27 at 11 27 23" src="https://user-images.githubusercontent.com/8056293/116180879-3bf1fd80-a74c-11eb-8cbe-8a09e55671c0.png">

**Comment by or-else** [comment]
> I tried the public server, and it looks like the server will not store files larger

The web.tinode.co is behind nginx. Our nginx is configured to reject very large files. Please do not use web.tinode.co for testing.
