### ISSUE TITLE
Can't logged into the application

### ISSUE THREAD

**Issue by ektapatel22** [tinode/tindroid#116]
I can compile the Android Project fetching from Github but Can't logged in or sign up. It gives an error like Failed to connect to /10.0.2.2 (port 6060)

Websocket error
    java.net.ConnectException: failed to connect to /10.0.2.2 (port 6060) from /:: (port 54448): connect failed: ETIMEDOUT (Connection timed out)
        at libcore.io.IoBridge.connect(IoBridge.java:142)
        at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
        at java.net.Socket.connect(Socket.java:621)
        at com.android.org.conscrypt.AbstractConscryptSocket.connect(AbstractConscryptSocket.java:156)
        at com.android.org.conscrypt.AbstractConscryptSocket.connect(AbstractConscryptSocket.java:140)
        at java.net.Socket.<init>(Socket.java:450)
        at java.net.Socket.<init>(Socket.java:218)
        at javax.net.ssl.SSLSocket.<init>(SSLSocket.java:931)
        at com.android.org.conscrypt.AbstractConscryptSocket.<init>(AbstractConscryptSocket.java:97)
        at com.android.org.conscrypt.OpenSSLSocketImpl.<init>(OpenSSLSocketImpl.java:41)
        at com.android.org.conscrypt.ConscryptEngineSocket.<init>(ConscryptEngineSocket.java:79)
        at com.android.org.conscrypt.Java8EngineSocket.<init>(Java8EngineSocket.java:42)
        at com.android.org.conscrypt.Platform.createEngineSocket(Platform.java:306)
        at com.android.org.conscrypt.OpenSSLSocketFactoryImpl.createSocket(OpenSSLSocketFactoryImpl.java:108)
        at co.tinode.tinodesdk.Connection$SNISocketFactory.createSocket(Connection.java:328)
        at co.tinode.tinodesdk.Connection$SNISocketFactory.createSocket(Connection.java:323)
        at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:448)

Please give a solution.

**Comment by or-else** [comment]
This is client app. It requires a server.
Please direct further questions to the forum.
