### ISSUE TITLE
W/Connection: Websocket error

### ISSUE THREAD

**Issue by reBiocoder** [tinode/tindroid#120]
**Describe the bug**
```
W/Connection: Websocket error
    javax.net.ssl.SSLHandshakeException: Handshake failed
        at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:396)
        at com.android.org.conscrypt.OpenSSLSocketImpl.waitForHandshake(OpenSSLSocketImpl.java:629)
        at com.android.org.conscrypt.OpenSSLSocketImpl.getInputStream(OpenSSLSocketImpl.java:591)
        at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:474)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0xb384bd40: Failure in SSL library, usually a protocol error
    error:100bd10c:SSL routines:ssl3_get_record:WRONG_VERSION_NUMBER (external/boringssl/src/ssl/s3_pkt.c:311 0xa9a6b5d7:0x00000000)
        at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
        at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:324)
        	... 4 more
```

**To Reproduce**
1. open tinode backend, grpc on 127.0.0.1:16060
2. username: 'alice', passward:'alice123'
3. See error

**Expected behavior**
```
W/Connection: Websocket error
    javax.net.ssl.SSLHandshakeException: Handshake failed
        at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:396)
        at com.android.org.conscrypt.OpenSSLSocketImpl.waitForHandshake(OpenSSLSocketImpl.java:629)
        at com.android.org.conscrypt.OpenSSLSocketImpl.getInputStream(OpenSSLSocketImpl.java:591)
        at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:474)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x9b03a280: Failure in SSL library, usually a protocol error
    error:100bd10c:SSL routines:ssl3_get_record:WRONG_VERSION_NUMBER (external/boringssl/src/ssl/s3_pkt.c:311 0xa9a6b5d7:0x00000000)
        at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
        at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:324)
        	... 4 more
D/Tinode: Disconnected for 'Handshake failed' (code: 1, remote: false);
W/Connection: Websocket error
    javax.net.ssl.SSLHandshakeException: Handshake failed
        at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:396)
        at com.android.org.conscrypt.OpenSSLSocketImpl.waitForHandshake(OpenSSLSocketImpl.java:629)
        at com.android.org.conscrypt.OpenSSLSocketImpl.getInputStream(OpenSSLSocketImpl.java:591)
        at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:474)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0xb384a1c0: Failure in SSL library, usually a protocol error
    error:100bd10c:SSL routines:ssl3_get_record:WRONG_VERSION_NUMBER (external/boringssl/src/ssl/s3_pkt.c:311 0xa9a6b5d7:0x00000000)
        at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
        at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:324)
        	... 4 more
```

**Screenshots**
![image](https://user-images.githubusercontent.com/39401819/163581974-7cea1980-c414-4060-be42-757f380c027f.png)
![image](https://user-images.githubusercontent.com/39401819/163582095-a774e066-de9b-40bf-9908-da60e557b736.png)

**Tindroid (please complete the following information):**
 - Version [e.g. 0.16.0-rc2]
 - Device [e.g. Stock Emulator or Pixel 2]
 - Android API Version [e.g. 28]

**Server**
- Type  your own setup: 127.0.0.1:6060
- Server type unmodified

**Additional context**
Attach server-side and client-side logs (logcat).

**Comment by or-else** [comment]
Please provide all requested information.

**Comment by reBiocoder** [comment]
> Please provide all requested information.

thanks for your reply! I'll rephrase the question.

**Comment by or-else** [comment]
It's been 3 months without updates. I assume it's either resolved or no longer relevant. Closing.
