### ISSUE TITLE
Tindroid crashes when playing long audios

### ISSUE THREAD

**Issue by sanmiguel2019** [tinode/tindroid#137]
**Describe the bug**

Tindroid can not play long audios, it just crashes. Not sure if this is simply because the audio is large or because large files are not stored in the database.

**To Reproduce**

Record a long audio that will be stored not in the database but as a file. Start to play audio. Tinode will crash.

**Tindroid (please complete the following information):**
 - Version: Tindroid Media (I updated it on December 12).
 - Device: Emulator or Pixel 3, telephone Samsung, Android version 13.

**Server**

- Tinode server version: 0.20.1
 - Database: MySQL
 - Server type: unmodified

**Additional context**

- Mimetypes of audio files in `fileuploads `table are saved as `video/mp4`. I don't know if that's how it should be.

- Emulator log:

```
E/MediaPlayerNative: prepareAsync called in state 1, mPlayer(0x0)
E/InputEventReceiver: Exception dispatching input event.
E/MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
E/MessageQueue-JNI: java.lang.IllegalStateException
        at android.media.MediaPlayer.prepareAsync(Native Method)
        at my.app.MessagesAdapter$MediaControl.ensurePlayerReady(MessagesAdapter.java:1426)
        at my.app.MessagesAdapter$SpanClicker.clickAudio(MessagesAdapter.java:1155)
        at my.app.MessagesAdapter$SpanClicker.onClick(MessagesAdapter.java:1091)
        at my.app.format.FullFormatter$4.onClick(FullFormatter.java:329)
        at android.text.method.LinkMovementMethod.onTouchEvent(LinkMovementMethod.java:232)
        at android.widget.TextView.onTouchEvent(TextView.java:11459)
        at android.view.View.dispatchTouchEvent(View.java:15004)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
        at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:498)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1899)
        at android.app.Activity.dispatchTouchEvent(Activity.java:4262)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:70)
        at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:456)
        at android.view.View.dispatchPointerEvent(View.java:15263)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6548)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6348)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5804)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5861)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5827)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5992)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5835)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6049)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5808)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5861)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5827)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5835)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5808)
E/MessageQueue-JNI:     at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8857)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8808)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8777)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:8980)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:267)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:335)
        at android.os.Looper.loopOnce(Looper.java:161)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7898)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: my.app, PID: 1692
    java.lang.IllegalStateException
        at android.media.MediaPlayer.prepareAsync(Native Method)
        at my.app.MessagesAdapter$MediaControl.ensurePlayerReady(MessagesAdapter.java:1426)
        at my.app.MessagesAdapter$SpanClicker.clickAudio(MessagesAdapter.java:1155)
        at my.app.MessagesAdapter$SpanClicker.onClick(MessagesAdapter.java:1091)
        at my.app.format.FullFormatter$4.onClick(FullFormatter.java:329)
        at android.text.method.LinkMovementMethod.onTouchEvent(LinkMovementMethod.java:232)
        at android.widget.TextView.onTouchEvent(TextView.java:11459)
        at android.view.View.dispatchTouchEvent(View.java:15004)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
        at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:498)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1899)
        at android.app.Activity.dispatchTouchEvent(Activity.java:4262)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:70)
        at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:456)
        at android.view.View.dispatchPointerEvent(View.java:15263)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6548)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6348)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5804)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5861)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5827)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5992)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5835)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6049)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5808)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5861)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5827)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5835)
E/AndroidRuntime:     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5808)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8857)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8808)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8777)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:8980)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:267)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:335)
        at android.os.Looper.loopOnce(Looper.java:161)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7898)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
I/Process: Sending signal. PID: 1692 SIG: 9
Disconnected from the target VM, address: 'localhost:61623', transport: 'socket'

```

**Comment by or-else** [comment]
This is interesting. It actually worked when I tested it, but something changed between development and release, possibly some updated dependencies affected it. 

It's definitely a bug in android. The error is `prepareAsync called in state 1`, but MediaPlayer.prepareAsync() is supposed to be called in state 1 (IDLE).

**Comment by or-else** [comment]
Found the bug, it's in my code.

**Comment by or-else** [comment]
Fixed in https://github.com/tinode/tindroid/commit/d1abd6e6b4d769b21d31d922906e4cf97150dde9. Thanks.

**Comment by sanmiguel2019** [comment]
Yes, now it works, thanks.
