### ISSUE TITLE
uid cannot notify authentication for accounts of type: co.tinode.account

### ISSUE THREAD

**Issue by shaniceweiwei** [tinode/tindroid#36]
REJECTING promise com.myapp.tinodesdk.PromisedReply@11c8b2
    java.lang.SecurityException: uid 1010341 cannot notify authentication for accounts of type: co.tinode.account
        at android.os.Parcel.createException(Parcel.java:1950)
        at android.os.Parcel.readException(Parcel.java:1918)
        at android.os.Parcel.readException(Parcel.java:1868)
        at android.accounts.IAccountManager$Stub$Proxy.accountAuthenticated(IAccountManager.java:1646)
        at android.accounts.AccountManager.notifyAccountAuthenticated(AccountManager.java:1062)
        at com.myapp.app.LoginOtpFragment.addAndroidAccount(LoginOtpFragment.java:249)
        at com.myapp.app.LoginOtpFragment.access$200(LoginOtpFragment.java:45)
        at com.myapp.app.LoginOtpFragment$2.onSuccess(LoginOtpFragment.java:196)
        at com.myapp.app.LoginOtpFragment$2.onSuccess(LoginOtpFragment.java:190)
        at com.myapp.tinodesdk.PromisedReply.callOnSuccess(PromisedReply.java:165)
        at com.myapp.tinodesdk.PromisedReply.resolve(PromisedReply.java:241)
        at com.myapp.tinodesdk.PromisedReply.handleSuccess(PromisedReply.java:197)
        at com.myapp.tinodesdk.PromisedReply.callOnSuccess(PromisedReply.java:171)
        at com.myapp.tinodesdk.PromisedReply.resolve(PromisedReply.java:241)
        at com.myapp.tinodesdk.PromisedReply.handleSuccess(PromisedReply.java:197)
        at com.myapp.tinodesdk.PromisedReply.callOnSuccess(PromisedReply.java:171)
        at com.myapp.tinodesdk.PromisedReply.resolve(PromisedReply.java:241)
        at com.myapp.tinodesdk.Tinode.dispatchPacket(Tinode.java:438)
        at com.myapp.tinodesdk.Tinode.access$500(Tinode.java:65)
        at com.myapp.tinodesdk.Tinode$1.onMessage(Tinode.java:309)
        at com.myapp.tinodesdk.Connection$TinodeWSClient.onMessage(Connection.java:200)
        at org.java_websocket.client.WebSocketClient.onWebsocketMessage(WebSocketClient.java:492)
        at org.java_websocket.drafts.Draft_6455.processFrame(Draft_6455.java:709)
        at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:367)
        at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:212)
        at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:417)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.accounts.AccountManagerService.accountAuthenticated(AccountManagerService.java:1698)
        at android.accounts.IAccountManager$Stub.onTransact(IAccountManager.java:563)
        at com.android.server.accounts.AccountManagerService.onTransact(AccountManagerService.java:1075)
        at android.os.Binder.execTransact(Binder.java:731)

**Comment by or-else** [comment]
What's the app version?

Please describe steps to reproduce.

**Comment by or-else** [comment]
It seems like you are integrating the SDK with your own app and the exception is happening in your code: `com.myapp.app.LoginOtpFragment.addAndroidAccount`

**Comment by shaniceweiwei** [comment]
sorry, i was using the old version, recompiled the latest one in github, working fine.
