### ISSUE TITLE
Recreating a just-deleted topic crashes the app

### ISSUE THREAD

**Issue by aforge** [tinode/tindroid#39]
1. Log in as alice
2. Delete the chat with Frank
3. Go to New Chat -> Find
4. Click on Frank in the Phone Contacts section
`
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: co.tinode.tindroid, PID: 3195
    java.lang.IllegalStateException: Restarter must be created only during owner's initialization stage
        at androidx.savedstate.SavedStateRegistryController.performRestore(SavedStateRegistryController.java:59)
        at androidx.fragment.app.Fragment.performCreate(Fragment.java:2527)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:843)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1235)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1301)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:710)
        at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2071)
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1861)
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1816)
        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1723)
        at androidx.fragment.app.FragmentManagerImpl$1.run(FragmentManagerImpl.java:146)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
`

**Comment by or-else** [comment]
Yep, I see this crash in crashlytics console.

**Comment by VladYatsenko** [comment]
Hello! I encountered the same error when developing my application. In my case, this happens when I refresh back stack

**Comment by or-else** [comment]
I see the crashes but I don't understand what exactly is their cause and how to fix it. Seems like a fragment is being restored from bundle at a wrong stage.

**Comment by aforge** [comment]
@VladYatsenko any way you can give instructions to reproduce in vanilla Tindroid?

**Comment by wttbddsk** [comment]
ya kak-to pofiksil, sam x3 kak

**Comment by VladYatsenko** [comment]
@wttbddsk Please show dependencies from build.gradle (app). do you use androidx? How do you clean the backstack and add a new fragment?

**Comment by VladYatsenko** [comment]
@aforge for me in my application this happens in such a case - I add the first fragment, then I add several fragments without detaching previous. then I need to go back to the first fragment. I clear backstack & add first fragment. the add code is executed, then I get this error.

**Comment by wttbddsk** [comment]
@VladYatsenko i have the same dependencies as tindroid(because actually it is tindroid), i just finish activity and have deleted intent.addflag, this helped me

**Comment by or-else** [comment]
@wttbddsk Can show the diff? Or send the patch?

**Comment by wttbddsk** [comment]
@or-else MessageActivity diff: https://www.diffchecker.com/GHrWYxOY
               FindAdapter diff: https://www.diffchecker.com/Vur612zH
try this, actually, i am not sure

**Comment by or-else** [comment]
Thanks! Will check it out later today.

**Comment by or-else** [comment]
There have been a lot of fixes related to `Restarter must be created only during owner's initialization stage`. I no longer see such crashes in Crashlytics. Closing. Feel free to reopen if crashes reappear.
