### ISSUE TITLE
New message not displaying

### ISSUE THREAD

**Issue by mudphilo** [tinode/tindroid#6]
When receiving new message the app is not able to display, in the logcat, it throws the below message

`
java.lang.NullPointerException: Attempt to invoke virtual method 'co.tinode.tinodesdk.LocalData$Payload co.tinode.tinodesdk.model.Subscription.getLocal()' on a null object reference
        at co.tinode.tindroid.db.SqlStore.msgReceived(SqlStore.java:202)
        at co.tinode.tinodesdk.Topic.routeData(Topic.java:1418)
        at co.tinode.tinodesdk.Tinode.dispatchPacket(Tinode.java:432)
        at co.tinode.tinodesdk.Tinode.access$500(Tinode.java:62)
        at co.tinode.tinodesdk.Tinode$1.onMessage(Tinode.java:302)
        at co.tinode.tinodesdk.Connection$TinodeWSClient.onMessage(Connection.java:202)
        at org.java_websocket.client.WebSocketClient.onWebsocketMessage(WebSocketClient.java:292)
        at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:417)
        at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:170)
        at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:229)
        at java.lang.Thread.run(Thread.java:761)
`

**Comment by or-else** [comment]
i fixed the cause of the crash but not the reason for the failed message
https://github.com/tinode/android-example/commit/a3720a4d1668fa0db6375e9144daa1a0ac692b78#diff-b679e628dcf89c16eb065a44de152a05R205
It also does not fix the underlying reason which I still cannot reproduce. Please do follow up so I would fix the path that leads to the crash. Thanks.

**Comment by or-else** [comment]
It has not been updated in a while. The code has changed substantially since it's been reported.
